// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Refahi.Modules.SupplyChain.Infrastructure.Persistence.Context;

#nullable disable

namespace Refahi.Modules.SupplyChain.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SupplyChainDbContext))]
    [Migration("20260426120000_SupplyChain_Supplier_AddLogoUrl")]
    partial class SupplyChain_Supplier_AddLogoUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("supplychain")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Refahi.Modules.SupplyChain.Domain.Aggregates.Agreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgreementNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("AgreementType")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ToDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgreementNo")
                        .IsUnique()
                        .HasFilter("\"AgreementNo\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("Status", "IsDeleted");

                    b.HasIndex("SupplierId", "Status");

                    b.ToTable("agreements", "supplychain");
                });

            modelBuilder.Entity("Refahi.Modules.SupplyChain.Domain.Aggregates.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BrandName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EconomicCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("integer");

                    b.Property<string>("RepresentativeName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RepresentativePhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasFilter("\"NationalId\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("ProvinceId", "CityId");

                    b.HasIndex("Status", "IsDeleted");

                    b.ToTable("suppliers", "supplychain");
                });

            modelBuilder.Entity("Refahi.Modules.SupplyChain.Domain.Entities.AgreementProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CommissionPercent")
                        .HasColumnType("numeric(5,2)");

                    b.Property<long>("CommissionPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("DeliveryType")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("DiscountedPrice")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<short>("ProductType")
                        .HasColumnType("smallint");

                    b.Property<short>("SalesModel")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgreementId");

                    b.HasIndex("AgreementId", "IsDeleted");

                    b.ToTable("agreement_products", "supplychain");
                });

            modelBuilder.Entity("Refahi.Modules.SupplyChain.Domain.Entities.SupplierAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("supplier_attachments", "supplychain");
                });

            modelBuilder.Entity("Refahi.Modules.SupplyChain.Domain.Entities.SupplierLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("supplier_links", "supplychain");
                });

            modelBuilder.Entity("Refahi.Modules.SupplyChain.Domain.Aggregates.Agreement", b =>
                {
                    b.HasOne("Refahi.Modules.SupplyChain.Domain.Aggregates.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Refahi.Modules.SupplyChain.Domain.Entities.AgreementProduct", b =>
                {
                    b.HasOne("Refahi.Modules.SupplyChain.Domain.Aggregates.Agreement", null)
                        .WithMany("Products")
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.SupplyChain.Domain.Entities.SupplierAttachment", b =>
                {
                    b.HasOne("Refahi.Modules.SupplyChain.Domain.Aggregates.Supplier", null)
                        .WithMany("Attachments")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.SupplyChain.Domain.Entities.SupplierLink", b =>
                {
                    b.HasOne("Refahi.Modules.SupplyChain.Domain.Aggregates.Supplier", null)
                        .WithMany("Links")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.SupplyChain.Domain.Aggregates.Agreement", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Refahi.Modules.SupplyChain.Domain.Aggregates.Supplier", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
