namespace Refahi.Modules.Orders.Application.Contracts.Dtos;

public sealed record OrderDto(
    Guid Id,
    string OrderNumber,
    Guid UserId,
    long TotalAmountMinor,
    long DiscountAmountMinor,
    long ShippingFeeMinor,
    string? DiscountCode,
    long DiscountCodeAmountMinor,
    long FinalAmountMinor,
    string Status,
    string PaymentState,
    string SourceModule,
    Guid? SourceReferenceId,
    string ReferenceType,
    Guid? ShippingAddressId,
    string? ShippingAddressSnapshotJson,
    DateOnly? DeliveryDate,
    short DeliveryTimeSlot,
    List<OrderItemDto> Items,
    DateTimeOffset CreatedAt,
    string Currency = "IRR",
    Guid? SourceOwnerId = null,
    Guid? SourceShopId = null,
    Guid? CreatedByUserId = null,
    long? GrossAmountMinor = null,
    decimal? CommissionPercent = null,
    long? CommissionAmountMinor = null,
    decimal? VatPercent = null,
    long? VatAmountMinor = null,
    long? RecipientNetAmountMinor = null,
    bool CanPay = false,
    string? PaymentUnavailableReason = null,
    DateTimeOffset? PayableUntil = null);

public sealed record OrderSummaryDto(
    Guid Id,
    string OrderNumber,
    long FinalAmountMinor,
    string Status,
    string SourceModule,
    int ItemCount,
    DateTimeOffset CreatedAt,
    string? FirstName,
    string? LastName,
    string? MobileNumber,
    string Currency = "IRR");
