FROM registry.refahi.xyz/refahigroup/refahiplus/api/ci/aspnet:10.0

WORKDIR /app

EXPOSE 8080

COPY .publish/api/ .

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
RUN playwright_node=$(find /app/.playwright/node -type f -name node | head -n 1) \
    && "$playwright_node" /app/.playwright/package/cli.js install --with-deps chromium

ENTRYPOINT ["dotnet", "Refahi.Api.dll"]
