// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Refahi.Modules.Cinema.Infrastructure.Persistence;

#nullable disable

namespace Refahi.Modules.Cinema.Infrastructure.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    partial class CinemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cinema")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Refahi.Modules.Cinema.Domain.CinemaOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("FeeMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IssuanceStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PayableUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SamfaCode")
                        .HasColumnType("text");

                    b.Property<string>("ScheduleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SubtotalMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("TicketCode")
                        .HasColumnType("text");

                    b.Property<long>("TotalMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("\"OrderId\" IS NOT NULL");

                    b.HasIndex("IssuanceStatus", "UpdatedAt");

                    b.HasIndex("ProviderKey", "ProviderOrderId")
                        .IsUnique()
                        .HasFilter("\"ProviderOrderId\" IS NOT NULL");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("orders", "cinema");
                });

            modelBuilder.Entity("Refahi.Modules.Cinema.Domain.CinemaProviderAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CinemaOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CinemaOrderId");

                    b.ToTable("provider_attempts", "cinema");
                });

            modelBuilder.Entity("Refahi.Modules.Cinema.Domain.CinemaProviderAttempt", b =>
                {
                    b.HasOne("Refahi.Modules.Cinema.Domain.CinemaOrder", null)
                        .WithMany("Attempts")
                        .HasForeignKey("CinemaOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Cinema.Domain.CinemaOrder", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
