// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Refahi.Modules.Flights.Infrastructure.Persistence;

#nullable disable

namespace Refahi.Modules.Flights.Infrastructure.Migrations
{
    [DbContext(typeof(FlightsDbContext))]
    [Migration("20260721052246_FlightAirportsReferenceData")]
    partial class FlightAirportsReferenceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flights")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Refahi.Modules.Flights.Domain.Aggregates.FlightAirportAgg.FlightAirport", b =>
                {
                    b.Property<string>("IataCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("iata_code");

                    b.Property<string>("AirportNameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("airport_name_en");

                    b.Property<string>("AirportNameFa")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("airport_name_fa");

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("city_code");

                    b.Property<string>("CityNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("city_name_en");

                    b.Property<string>("CityNameFa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("city_name_fa");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("country_name_en");

                    b.Property<string>("CountryNameFa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("country_name_fa");

                    b.Property<string>("IcaoCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("icao_code");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean")
                        .HasColumnName("is_popular");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_version");

                    b.Property<string>("TranslationSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("translation_source");

                    b.HasKey("IataCode");

                    b.HasIndex("IcaoCode")
                        .HasDatabaseName("ix_flight_airports_icao_code");

                    b.HasIndex("IsActive", "IsPopular")
                        .HasDatabaseName("ix_flight_airports_active_popular");

                    b.ToTable("airports", "flights");
                });

            modelBuilder.Entity("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.FlightBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("IssueFailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("issue_failure_reason");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_bookings_idempotency_key");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_bookings_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_flight_bookings_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_flight_bookings_user_id");

                    b.ToTable("flight_bookings", "flights");
                });

            modelBuilder.Entity("Refahi.Modules.Flights.Domain.Aggregates.FlightOfferSnapshotAgg.FlightOfferSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("OfferToken")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("offer_token");

                    b.Property<string>("ProviderFareSourceCode")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("provider_fare_source_code");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderSearchId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_search_id");

                    b.Property<string>("ProviderSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("provider_snapshot");

                    b.Property<string>("ProviderTraceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_trace_id");

                    b.Property<string>("PublicOfferSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("public_offer_snapshot");

                    b.Property<long>("TotalFareAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_fare_amount");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_flight_search_offer_snapshots_expires_at_utc");

                    b.HasIndex("OfferToken")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_search_offer_snapshots_offer_token");

                    b.ToTable("flight_search_offer_snapshots", "flights");
                });

            modelBuilder.Entity("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.FlightBooking", b =>
                {
                    b.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.CancellationQuoteSnapshot", "LatestCancellationQuote", b1 =>
                        {
                            b1.Property<Guid>("FlightBookingId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ExpiresAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("latest_cancellation_quote_expires_at_utc");

                            b1.Property<string>("ProviderCancellationQuoteId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("latest_cancellation_quote_provider_quote_id");

                            b1.Property<string>("ProviderTraceId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("latest_cancellation_quote_provider_trace_id");

                            b1.Property<DateTime>("QuotedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("latest_cancellation_quote_quoted_at_utc");

                            b1.Property<string>("SnapshotJson")
                                .HasColumnType("jsonb")
                                .HasColumnName("latest_cancellation_quote_snapshot");

                            b1.HasKey("FlightBookingId");

                            b1.ToTable("flight_bookings", "flights");

                            b1.WithOwner()
                                .HasForeignKey("FlightBookingId");

                            b1.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.Money", "PenaltyAmount", b2 =>
                                {
                                    b2.Property<Guid>("CancellationQuoteSnapshotFlightBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("latest_cancellation_quote_penalty_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("latest_cancellation_quote_penalty_currency");

                                    b2.HasKey("CancellationQuoteSnapshotFlightBookingId");

                                    b2.ToTable("flight_bookings", "flights");

                                    b2.WithOwner()
                                        .HasForeignKey("CancellationQuoteSnapshotFlightBookingId");
                                });

                            b1.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.Money", "RefundAmount", b2 =>
                                {
                                    b2.Property<Guid>("CancellationQuoteSnapshotFlightBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("latest_cancellation_quote_refund_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("latest_cancellation_quote_refund_currency");

                                    b2.HasKey("CancellationQuoteSnapshotFlightBookingId");

                                    b2.ToTable("flight_bookings", "flights");

                                    b2.WithOwner()
                                        .HasForeignKey("CancellationQuoteSnapshotFlightBookingId");
                                });

                            b1.Navigation("PenaltyAmount")
                                .IsRequired();

                            b1.Navigation("RefundAmount")
                                .IsRequired();
                        });

                    b.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.ContactInfo", "Contact", b1 =>
                        {
                            b1.Property<Guid>("FlightBookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("MobileNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("contact_mobile_number");

                            b1.HasKey("FlightBookingId");

                            b1.ToTable("flight_bookings", "flights");

                            b1.WithOwner()
                                .HasForeignKey("FlightBookingId");
                        });

                    b.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.FareBreakdown", "FareBreakdown", b1 =>
                        {
                            b1.Property<Guid>("FlightBookingId")
                                .HasColumnType("uuid");

                            b1.HasKey("FlightBookingId");

                            b1.ToTable("flight_bookings", "flights");

                            b1.WithOwner()
                                .HasForeignKey("FlightBookingId");

                            b1.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.Money", "BaseFare", b2 =>
                                {
                                    b2.Property<Guid>("FareBreakdownFlightBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("base_fare_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("base_fare_currency");

                                    b2.HasKey("FareBreakdownFlightBookingId");

                                    b2.ToTable("flight_bookings", "flights");

                                    b2.WithOwner()
                                        .HasForeignKey("FareBreakdownFlightBookingId");
                                });

                            b1.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.Money", "Discount", b2 =>
                                {
                                    b2.Property<Guid>("FareBreakdownFlightBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("discount_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("discount_currency");

                                    b2.HasKey("FareBreakdownFlightBookingId");

                                    b2.ToTable("flight_bookings", "flights");

                                    b2.WithOwner()
                                        .HasForeignKey("FareBreakdownFlightBookingId");
                                });

                            b1.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.Money", "Fees", b2 =>
                                {
                                    b2.Property<Guid>("FareBreakdownFlightBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("fees_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("fees_currency");

                                    b2.HasKey("FareBreakdownFlightBookingId");

                                    b2.ToTable("flight_bookings", "flights");

                                    b2.WithOwner()
                                        .HasForeignKey("FareBreakdownFlightBookingId");
                                });

                            b1.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.Money", "PayableAmount", b2 =>
                                {
                                    b2.Property<Guid>("FareBreakdownFlightBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("payable_amount_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("payable_amount_currency");

                                    b2.HasKey("FareBreakdownFlightBookingId");

                                    b2.ToTable("flight_bookings", "flights");

                                    b2.WithOwner()
                                        .HasForeignKey("FareBreakdownFlightBookingId");
                                });

                            b1.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.Money", "Taxes", b2 =>
                                {
                                    b2.Property<Guid>("FareBreakdownFlightBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("taxes_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("taxes_currency");

                                    b2.HasKey("FareBreakdownFlightBookingId");

                                    b2.ToTable("flight_bookings", "flights");

                                    b2.WithOwner()
                                        .HasForeignKey("FareBreakdownFlightBookingId");
                                });

                            b1.Navigation("BaseFare")
                                .IsRequired();

                            b1.Navigation("Discount")
                                .IsRequired();

                            b1.Navigation("Fees")
                                .IsRequired();

                            b1.Navigation("PayableAmount")
                                .IsRequired();

                            b1.Navigation("Taxes")
                                .IsRequired();
                        });

                    b.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.ProviderBookingSnapshot", "ProviderBooking", b1 =>
                        {
                            b1.Property<Guid>("FlightBookingId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("BookedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("provider_booked_at_utc");

                            b1.Property<string>("ProviderBookingCaption")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("provider_booking_caption");

                            b1.Property<string>("ProviderBookingId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider_booking_id");

                            b1.Property<string>("ProviderPnr")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("provider_pnr");

                            b1.Property<string>("ProviderTraceId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider_booking_trace_id");

                            b1.Property<string>("SnapshotJson")
                                .HasColumnType("jsonb")
                                .HasColumnName("provider_booking_snapshot");

                            b1.HasKey("FlightBookingId");

                            b1.ToTable("flight_bookings", "flights");

                            b1.WithOwner()
                                .HasForeignKey("FlightBookingId");
                        });

                    b.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.ProviderSnapshot", "Provider", b1 =>
                        {
                            b1.Property<Guid>("FlightBookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ProviderCaption")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider_caption");

                            b1.Property<string>("ProviderId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider_id");

                            b1.Property<string>("ProviderName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("provider_name");

                            b1.Property<string>("ProviderTraceId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider_trace_id");

                            b1.Property<string>("SnapshotJson")
                                .HasColumnType("jsonb")
                                .HasColumnName("provider_snapshot");

                            b1.HasKey("FlightBookingId");

                            b1.ToTable("flight_bookings", "flights");

                            b1.WithOwner()
                                .HasForeignKey("FlightBookingId");
                        });

                    b.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.SelectedFareSnapshot", "SelectedFare", b1 =>
                        {
                            b1.Property<Guid>("FlightBookingId")
                                .HasColumnType("uuid")
                                .HasColumnName("flight_booking_id");

                            b1.Property<string>("BookingClass")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("booking_class");

                            b1.Property<string>("CabinClass")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("cabin_class");

                            b1.Property<string>("FareCaption")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("fare_caption");

                            b1.Property<string>("FareRulesSnapshotJson")
                                .HasColumnType("jsonb")
                                .HasColumnName("fare_rules_snapshot");

                            b1.Property<string>("ProviderFareId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider_fare_id");

                            b1.Property<string>("ProviderTraceId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider_trace_id");

                            b1.HasKey("FlightBookingId");

                            b1.ToTable("flight_offer_snapshots", "flights");

                            b1.WithOwner()
                                .HasForeignKey("FlightBookingId");
                        });

                    b.OwnsMany("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.Entities.CancellationRequest", "CancellationRequests", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("CompletedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at_utc");

                            b1.Property<string>("FailureReason")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("failure_reason");

                            b1.Property<string>("ProviderCancellationId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider_cancellation_id");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("reason");

                            b1.Property<DateTime>("RequestedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("requested_at_utc");

                            b1.Property<short>("Status")
                                .HasColumnType("smallint")
                                .HasColumnName("status");

                            b1.Property<Guid>("flight_booking_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("flight_booking_id")
                                .HasDatabaseName("ix_flight_cancellation_requests_booking_id");

                            b1.ToTable("flight_cancellation_requests", "flights");

                            b1.WithOwner()
                                .HasForeignKey("flight_booking_id");

                            b1.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.CancellationQuoteSnapshot", "Quote", b2 =>
                                {
                                    b2.Property<Guid>("CancellationRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime?>("ExpiresAtUtc")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("quote_expires_at_utc");

                                    b2.Property<string>("ProviderCancellationQuoteId")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("quote_provider_quote_id");

                                    b2.Property<string>("ProviderTraceId")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("quote_provider_trace_id");

                                    b2.Property<DateTime>("QuotedAtUtc")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("quote_quoted_at_utc");

                                    b2.Property<string>("SnapshotJson")
                                        .HasColumnType("jsonb")
                                        .HasColumnName("quote_snapshot");

                                    b2.HasKey("CancellationRequestId");

                                    b2.ToTable("flight_cancellation_requests", "flights");

                                    b2.WithOwner()
                                        .HasForeignKey("CancellationRequestId");

                                    b2.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.Money", "PenaltyAmount", b3 =>
                                        {
                                            b3.Property<Guid>("CancellationQuoteSnapshotCancellationRequestId")
                                                .HasColumnType("uuid");

                                            b3.Property<long>("Amount")
                                                .HasColumnType("bigint")
                                                .HasColumnName("quote_penalty_amount");

                                            b3.Property<string>("Currency")
                                                .IsRequired()
                                                .HasMaxLength(3)
                                                .HasColumnType("character varying(3)")
                                                .HasColumnName("quote_penalty_currency");

                                            b3.HasKey("CancellationQuoteSnapshotCancellationRequestId");

                                            b3.ToTable("flight_cancellation_requests", "flights");

                                            b3.WithOwner()
                                                .HasForeignKey("CancellationQuoteSnapshotCancellationRequestId");
                                        });

                                    b2.OwnsOne("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.ValueObjects.Money", "RefundAmount", b3 =>
                                        {
                                            b3.Property<Guid>("CancellationQuoteSnapshotCancellationRequestId")
                                                .HasColumnType("uuid");

                                            b3.Property<long>("Amount")
                                                .HasColumnType("bigint")
                                                .HasColumnName("quote_refund_amount");

                                            b3.Property<string>("Currency")
                                                .IsRequired()
                                                .HasMaxLength(3)
                                                .HasColumnType("character varying(3)")
                                                .HasColumnName("quote_refund_currency");

                                            b3.HasKey("CancellationQuoteSnapshotCancellationRequestId");

                                            b3.ToTable("flight_cancellation_requests", "flights");

                                            b3.WithOwner()
                                                .HasForeignKey("CancellationQuoteSnapshotCancellationRequestId");
                                        });

                                    b2.Navigation("PenaltyAmount")
                                        .IsRequired();

                                    b2.Navigation("RefundAmount")
                                        .IsRequired();
                                });

                            b1.Navigation("Quote")
                                .IsRequired();
                        });

                    b.OwnsMany("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.Entities.FlightSegment", "Segments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AirlineCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("airline_code");

                            b1.Property<string>("AirlineName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("airline_name");

                            b1.Property<DateTime>("ArrivalAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("arrival_at_utc");

                            b1.Property<DateTime>("DepartureAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("departure_at_utc");

                            b1.Property<string>("DestinationAirportCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("destination_airport_code");

                            b1.Property<string>("DestinationCaption")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("destination_caption");

                            b1.Property<string>("FlightNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("flight_number");

                            b1.Property<string>("OriginAirportCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("origin_airport_code");

                            b1.Property<string>("OriginCaption")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("origin_caption");

                            b1.Property<string>("ProviderSegmentId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider_segment_id");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer")
                                .HasColumnName("sequence");

                            b1.Property<Guid>("flight_booking_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("flight_booking_id", "Sequence")
                                .IsUnique()
                                .HasDatabaseName("ux_flight_booking_segments_booking_sequence");

                            b1.ToTable("flight_booking_segments", "flights");

                            b1.WithOwner()
                                .HasForeignKey("flight_booking_id");
                        });

                    b.OwnsMany("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.Entities.IssuedTicket", "IssuedTickets", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("IssuedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("issued_at_utc");

                            b1.Property<Guid>("PassengerId")
                                .HasColumnType("uuid")
                                .HasColumnName("passenger_id");

                            b1.Property<string>("PassengerNameSnapshot")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("passenger_name_snapshot");

                            b1.Property<string>("ProviderTicketId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider_ticket_id");

                            b1.Property<string>("ProviderTraceId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider_trace_id");

                            b1.Property<string>("SnapshotJson")
                                .HasColumnType("jsonb")
                                .HasColumnName("ticket_snapshot");

                            b1.Property<string>("TicketNumber")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ticket_number");

                            b1.Property<Guid>("flight_booking_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TicketNumber")
                                .HasDatabaseName("ix_flight_booking_tickets_ticket_number");

                            b1.HasIndex("flight_booking_id")
                                .HasDatabaseName("ix_flight_booking_tickets_booking_id");

                            b1.ToTable("flight_booking_tickets", "flights");

                            b1.WithOwner()
                                .HasForeignKey("flight_booking_id");
                        });

                    b.OwnsMany("Refahi.Modules.Flights.Domain.Aggregates.FlightBookingAgg.Entities.Passenger", "Passengers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("BirthDate")
                                .HasColumnType("date")
                                .HasColumnName("birth_date");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("last_name");

                            b1.Property<string>("NationalCode")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("national_code");

                            b1.Property<string>("NationalityCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("nationality_code");

                            b1.Property<string>("PassportNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("passport_number");

                            b1.Property<short>("Type")
                                .HasColumnType("smallint")
                                .HasColumnName("type");

                            b1.Property<Guid>("flight_booking_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("flight_booking_id")
                                .HasDatabaseName("ix_flight_booking_passengers_booking_id");

                            b1.ToTable("flight_booking_passengers", "flights");

                            b1.WithOwner()
                                .HasForeignKey("flight_booking_id");
                        });

                    b.Navigation("CancellationRequests");

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("FareBreakdown")
                        .IsRequired();

                    b.Navigation("IssuedTickets");

                    b.Navigation("LatestCancellationQuote");

                    b.Navigation("Passengers");

                    b.Navigation("Provider")
                        .IsRequired();

                    b.Navigation("ProviderBooking");

                    b.Navigation("Segments");

                    b.Navigation("SelectedFare")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
