// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Refahi.Modules.Charge.Infrastructure.Persistence.Context;

#nullable disable

namespace Refahi.Modules.Charge.Infrastructure.Migrations
{
    [DbContext(typeof(ChargeDbContext))]
    [Migration("20260701131031_Charge-Init")]
    partial class ChargeInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("charge")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Refahi.Modules.Charge.Domain.Aggregates.ChargeFulfillmentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChargeRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_request_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EniacResultCode")
                        .HasColumnType("integer")
                        .HasColumnName("eniac_result_code");

                    b.Property<long>("LatencyMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<string>("OperatorResultCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operator_result_code");

                    b.Property<string>("ProviderRrn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_rrn");

                    b.Property<string>("ProviderTraceId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("provider_trace_id");

                    b.Property<string>("RequestSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_snapshot_json");

                    b.Property<string>("ResponseSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_snapshot_json");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ChargeRequestId", "CreatedAt");

                    b.ToTable("charge_fulfillment_attempts", "charge");
                });

            modelBuilder.Entity("Refahi.Modules.Charge.Domain.Aggregates.ChargeMarkupRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<long>("FixedAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("fixed_amount_minor");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<short?>("Operator")
                        .HasColumnType("smallint")
                        .HasColumnName("operator");

                    b.Property<decimal>("Percent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("percent");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<short?>("ServiceType")
                        .HasColumnType("smallint")
                        .HasColumnName("service_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Operator", "ServiceType", "EffectiveFrom")
                        .HasDatabaseName("ix_charge_markup_scope");

                    b.ToTable("charge_markup_rules", "charge");
                });

            modelBuilder.Entity("Refahi.Modules.Charge.Domain.Aggregates.ChargePin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<Guid>("ChargeRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_request_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedCode")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("encrypted_code");

                    b.Property<string>("EncryptedSerial")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("encrypted_serial");

                    b.HasKey("Id");

                    b.HasIndex("ChargeRequestId");

                    b.ToTable("charge_pins", "charge");
                });

            modelBuilder.Entity("Refahi.Modules.Charge.Domain.Aggregates.ChargeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerInvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("customer_invoice_number");

                    b.Property<string>("DestinationMobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("destination_mobile_number");

                    b.Property<int?>("EniacResultCode")
                        .HasColumnType("integer")
                        .HasColumnName("eniac_result_code");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_at");

                    b.Property<long>("FinalAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("final_amount_minor");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fulfilled_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<long>("MarkupAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("markup_amount_minor");

                    b.Property<long>("MarkupFixedMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("markup_fixed_minor");

                    b.Property<decimal>("MarkupPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("markup_percent");

                    b.Property<Guid?>("MarkupRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("markup_rule_id");

                    b.Property<DateTime?>("NextReconciliationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_reconciliation_at");

                    b.Property<short>("Operator")
                        .HasColumnType("smallint")
                        .HasColumnName("operator");

                    b.Property<string>("OperatorResultCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operator_result_code");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("OriginMobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin_mobile_number");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<int>("PayBill")
                        .HasColumnType("integer")
                        .HasColumnName("pay_bill");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<int?>("PinCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("pin_category_id");

                    b.Property<int>("PinCount")
                        .HasColumnType("integer")
                        .HasColumnName("pin_count");

                    b.Property<string>("ProcessingLeaseOwner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("processing_lease_owner");

                    b.Property<DateTime?>("ProcessingLeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_lease_until");

                    b.Property<string>("ProductCaption")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("product_caption");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("integer")
                        .HasColumnName("product_category");

                    b.Property<string>("ProductSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("product_snapshot_json");

                    b.Property<long>("ProviderCostMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("provider_cost_minor");

                    b.Property<string>("ProviderMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("provider_message");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderProductId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("provider_product_id");

                    b.Property<string>("ProviderRrn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_rrn");

                    b.Property<string>("ProviderTraceId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("provider_trace_id");

                    b.Property<int>("ReconciliationCount")
                        .HasColumnType("integer")
                        .HasColumnName("reconciliation_count");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<short>("ServiceType")
                        .HasColumnType("smallint")
                        .HasColumnName("service_type");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerInvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_charge_requests_invoice");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_charge_requests_order_id")
                        .HasFilter("order_id IS NOT NULL");

                    b.HasIndex("Status", "NextReconciliationAt")
                        .HasDatabaseName("ix_charge_requests_work");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_charge_requests_user_idempotency");

                    b.ToTable("charge_requests", "charge");
                });

            modelBuilder.Entity("Refahi.Modules.Charge.Domain.Aggregates.ChargeFulfillmentAttempt", b =>
                {
                    b.HasOne("Refahi.Modules.Charge.Domain.Aggregates.ChargeRequest", null)
                        .WithMany("Attempts")
                        .HasForeignKey("ChargeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Charge.Domain.Aggregates.ChargePin", b =>
                {
                    b.HasOne("Refahi.Modules.Charge.Domain.Aggregates.ChargeRequest", null)
                        .WithMany("Pins")
                        .HasForeignKey("ChargeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Charge.Domain.Aggregates.ChargeRequest", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Pins");
                });
#pragma warning restore 612, 618
        }
    }
}
