// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Refahi.Modules.Hotels.Infrastructure.Persistence;

#nullable disable

namespace Refahi.Modules.Hotels.Infrastructure.Migrations
{
    [DbContext(typeof(HotelsDbContext))]
    [Migration("20251202215125_Hotels_Init")]
    partial class Hotels_Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Hotels")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("BoardType")
                        .HasColumnType("integer")
                        .HasColumnName("BoardType");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LockedUntil");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("Provider");

                    b.Property<string>("ProviderBookingCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ProviderBookingCode");

                    b.Property<long>("ProviderHotelId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProviderHotelId");

                    b.Property<long>("ProviderRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProviderRoomId");

                    b.Property<int>("RoomsCount")
                        .HasColumnType("integer")
                        .HasColumnName("RoomsCount");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("hotel_bookings", "Hotels");
                });

            modelBuilder.Entity("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.Booking", b =>
                {
                    b.OwnsOne("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.ValueObjects.Money", "BasePrice", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("BasePriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("BasePriceCurrency");

                            b1.HasKey("BookingId");

                            b1.ToTable("hotel_bookings", "Hotels");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.ValueObjects.Money", "CustomerPrice", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("CustomerPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("CustomerPriceCurrency");

                            b1.HasKey("BookingId");

                            b1.ToTable("hotel_bookings", "Hotels");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.ValueObjects.Money", "MarginAmount", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("MarginAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("MarginCurrency");

                            b1.HasKey("BookingId");

                            b1.ToTable("hotel_bookings", "Hotels");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.ValueObjects.DateRange", "StayRange", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("CheckIn")
                                .HasColumnType("date")
                                .HasColumnName("CheckIn");

                            b1.Property<DateOnly>("CheckOut")
                                .HasColumnType("date")
                                .HasColumnName("CheckOut");

                            b1.HasKey("BookingId");

                            b1.ToTable("hotel_bookings", "Hotels");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsMany("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.ValueObjects.Guest", "Guests", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Age")
                                .HasColumnType("integer")
                                .HasColumnName("Age");

                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("FullName");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("Type");

                            b1.HasKey("Id");

                            b1.HasIndex("BookingId");

                            b1.ToTable("hotel_booking_guests", "Hotels");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.ValueObjects.Voucher", "Voucher", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Url")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("VoucherUrl");

                            b1.Property<string>("VoucherNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("VoucherNumber");

                            b1.HasKey("BookingId");

                            b1.ToTable("hotel_bookings", "Hotels");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("BasePrice")
                        .IsRequired();

                    b.Navigation("CustomerPrice")
                        .IsRequired();

                    b.Navigation("Guests");

                    b.Navigation("MarginAmount")
                        .IsRequired();

                    b.Navigation("StayRange")
                        .IsRequired();

                    b.Navigation("Voucher");
                });
#pragma warning restore 612, 618
        }
    }
}
