// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Refahi.Modules.Hotels.Infrastructure.Persistence;

#nullable disable

namespace Refahi.Modules.Hotels.Infrastructure.Migrations
{
    [DbContext(typeof(HotelsDbContext))]
    [Migration("20260628210648_Hotels-AddBookingSagaState")]
    partial class HotelsAddBookingSagaState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hotels")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("BoardType")
                        .HasColumnType("integer")
                        .HasColumnName("BoardType");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LockedUntil");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("Provider");

                    b.Property<string>("ProviderBookingCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ProviderBookingCode");

                    b.Property<long>("ProviderHotelId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProviderHotelId");

                    b.Property<long>("ProviderRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProviderRoomId");

                    b.Property<int>("RoomsCount")
                        .HasColumnType("integer")
                        .HasColumnName("RoomsCount");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("hotel_bookings", "hotels");
                });

            modelBuilder.Entity("Refahi.Modules.Hotels.Domain.Aggregates.HotelBookingSagaAgg.HotelBookingSagaState", b =>
                {
                    b.Property<Guid>("SagaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("HotelRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_request_id");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<short>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("payment_status");

                    b.Property<short>("ProviderBookingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("provider_booking_status");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SagaId");

                    b.HasIndex("HotelRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_hotel_booking_sagas_hotel_request_id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_hotel_booking_sagas_order_id")
                        .HasFilter("\"order_id\" IS NOT NULL");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_hotel_booking_sagas_status_updated_at");

                    b.ToTable("hotel_booking_sagas", "hotels");
                });

            modelBuilder.Entity("Refahi.Modules.Hotels.Domain.Aggregates.HotelRequestAgg.HotelRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Breakdown")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("breakdown");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("IRR")
                        .HasColumnName("currency");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_at");

                    b.Property<string>("Fees")
                        .HasColumnType("jsonb")
                        .HasColumnName("fees");

                    b.Property<string>("GuestInfoSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("guest_info_snapshot");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("ProviderBookingCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_booking_code");

                    b.Property<DateTime?>("ProviderConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provider_confirmed_at");

                    b.Property<long>("ProviderHotelId")
                        .HasColumnType("bigint")
                        .HasColumnName("provider_hotel_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider_name");

                    b.Property<long>("ProviderRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("provider_room_id");

                    b.Property<string>("SearchCriteriaSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("search_criteria_snapshot");

                    b.Property<string>("SelectedHotelSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_hotel_snapshot");

                    b.Property<string>("SelectedRoomSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_room_snapshot");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<long>("TotalPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_hotel_requests_order_id")
                        .HasFilter("\"order_id\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_hotel_requests_user_id");

                    b.HasIndex("Status", "ExpireAt")
                        .HasDatabaseName("ix_hotel_requests_status_expire_at");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_hotel_requests_user_id_idempotency_key");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_hotel_requests_user_id_status");

                    b.ToTable("hotel_requests", "hotels");
                });

            modelBuilder.Entity("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.Booking", b =>
                {
                    b.OwnsOne("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.ValueObjects.Money", "BasePrice", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("BasePriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("BasePriceCurrency");

                            b1.HasKey("BookingId");

                            b1.ToTable("hotel_bookings", "hotels");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.ValueObjects.Money", "CustomerPrice", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("CustomerPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("CustomerPriceCurrency");

                            b1.HasKey("BookingId");

                            b1.ToTable("hotel_bookings", "hotels");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.ValueObjects.Money", "MarginAmount", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("MarginAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("MarginCurrency");

                            b1.HasKey("BookingId");

                            b1.ToTable("hotel_bookings", "hotels");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.ValueObjects.DateRange", "StayRange", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("CheckIn")
                                .HasColumnType("date")
                                .HasColumnName("CheckIn");

                            b1.Property<DateOnly>("CheckOut")
                                .HasColumnType("date")
                                .HasColumnName("CheckOut");

                            b1.HasKey("BookingId");

                            b1.ToTable("hotel_bookings", "hotels");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsMany("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.ValueObjects.Guest", "Guests", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Age")
                                .HasColumnType("integer")
                                .HasColumnName("Age");

                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("FullName");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("Type");

                            b1.HasKey("Id");

                            b1.HasIndex("BookingId");

                            b1.ToTable("hotel_booking_guests", "hotels");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("Refahi.Modules.Hotels.Domain.Aggregates.BookingAgg.ValueObjects.Voucher", "Voucher", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Url")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("VoucherUrl");

                            b1.Property<string>("VoucherNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("VoucherNumber");

                            b1.HasKey("BookingId");

                            b1.ToTable("hotel_bookings", "hotels");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("BasePrice")
                        .IsRequired();

                    b.Navigation("CustomerPrice")
                        .IsRequired();

                    b.Navigation("Guests");

                    b.Navigation("MarginAmount")
                        .IsRequired();

                    b.Navigation("StayRange")
                        .IsRequired();

                    b.Navigation("Voucher");
                });
#pragma warning restore 612, 618
        }
    }
}
