// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Refahi.Modules.Wallets.Infrastructure.Persistence.Context;

#nullable disable

namespace Refahi.Modules.Wallets.Infrastructure.Migrations
{
    [DbContext(typeof(WalletsDbContext))]
    [Migration("20260225201141_Wallets-Init")]
    partial class WalletsInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wallets")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Refahi.Modules.Wallets.Domain.Aggregates.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_entry_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at");

                    b.Property<short>("EntryType")
                        .HasColumnType("smallint")
                        .HasColumnName("entry_type");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text")
                        .HasColumnName("external_reference");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<short>("OperationType")
                        .HasColumnType("smallint")
                        .HasColumnName("operation_type");

                    b.Property<Guid?>("RelatedEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entry_id");

                    b.Property<short>("RelationType")
                        .HasColumnType("smallint")
                        .HasColumnName("relation_type");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .HasDatabaseName("idx_ledger_operation");

                    b.HasIndex("RelatedEntryId");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("idx_ledger_wallet");

                    b.HasIndex("WalletId", "CreatedAt")
                        .HasDatabaseName("idx_ledger_wallet_created_at");

                    b.ToTable("ledger_entries", "wallets");
                });

            modelBuilder.Entity("Refahi.Modules.Wallets.Domain.Aggregates.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<short>("WalletType")
                        .HasColumnType("smallint")
                        .HasColumnName("wallet_type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("idx_wallets_owner");

                    b.ToTable("wallets", "wallets");
                });

            modelBuilder.Entity("Refahi.Modules.Wallets.Infrastructure.Persistence.Models.IdempotencyKeyRecord", b =>
                {
                    b.Property<Guid>("IdempotencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<short>("OperationType")
                        .HasColumnType("smallint")
                        .HasColumnName("operation_type");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("request_hash");

                    b.Property<long?>("ResultBalanceAvailableMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("result_balance_available_minor");

                    b.PrimitiveCollection<Guid[]>("ResultLedgerEntryIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("result_ledger_entry_ids");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("IdempotencyId");

                    b.HasIndex("WalletId", "IdempotencyKey", "OperationType")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_wallet_key_optype");

                    b.ToTable("idempotency_keys", "wallets");
                });

            modelBuilder.Entity("Refahi.Modules.Wallets.Infrastructure.Persistence.Models.WalletBalanceRecord", b =>
                {
                    b.Property<Guid>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.Property<long>("AvailableMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("available_minor");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("LastLedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_ledger_entry_id");

                    b.Property<long>("PendingMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("pending_minor");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("WalletId");

                    b.ToTable("wallet_balances", "wallets");
                });

            modelBuilder.Entity("Refahi.Modules.Wallets.Domain.Aggregates.LedgerEntry", b =>
                {
                    b.HasOne("Refahi.Modules.Wallets.Domain.Aggregates.LedgerEntry", null)
                        .WithMany()
                        .HasForeignKey("RelatedEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Refahi.Modules.Wallets.Domain.ValueObjects.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("LedgerEntryId")
                                .HasColumnType("uuid");

                            b1.Property<long>("AmountMinor")
                                .HasColumnType("bigint")
                                .HasColumnName("amount_minor");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("LedgerEntryId");

                            b1.ToTable("ledger_entries", "wallets");

                            b1.WithOwner()
                                .HasForeignKey("LedgerEntryId");
                        });

                    b.Navigation("Money");
                });
#pragma warning restore 612, 618
        }
    }
}
