// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Refahi.Modules.PaymentGateway.Infrastructure.Persistence.Context;

#nullable disable

namespace Refahi.Modules.PaymentGateway.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentGatewayDbContext))]
    [Migration("20260510055449_InitialPaymentGatewaySchema")]
    partial class InitialPaymentGatewaySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payment_gateway")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Refahi.Modules.PaymentGateway.Domain.Aggregates.PaymentGatewaySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FailedCallbackUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failed_callback_url");

                    b.Property<DateTimeOffset>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<short>("Provider")
                        .HasColumnType("smallint")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderRawCallbackJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("provider_raw_callback");

                    b.Property<string>("ProviderRefNum")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_ref_num");

                    b.Property<int?>("ProviderResultCode")
                        .HasColumnType("integer")
                        .HasColumnName("provider_result_code");

                    b.Property<string>("ProviderResultDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("provider_result_description");

                    b.Property<string>("ProviderSecurePan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_secure_pan");

                    b.Property<string>("ProviderToken")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("provider_token");

                    b.Property<string>("ProviderTraceNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_trace_no");

                    b.Property<string>("ReturnBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("return_base_url");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("SucceededCallbackUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("succeeded_callback_url");

                    b.Property<Guid?>("TopUpLedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("topup_ledger_entry_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedAt")
                        .HasDatabaseName("idx_pg_sessions_initiated_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_pg_sessions_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_pg_sessions_user");

                    b.ToTable("sessions", "payment_gateway");
                });
#pragma warning restore 612, 618
        }
    }
}
