"""Generate the reviewed, self-contained PostgreSQL import and source audit.

Run from any directory with Python 3; no database/network access is performed.
SQL is also embedded and executed by FlightAirportDataSeeder.
"""
from pathlib import Path
import gzip
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'src/Refahi.Modules.Flights.Infrastructure/Data'
SOURCE = DATA / 'search-catalog-20260906'
OUT = ROOT / 'scripts/flights/search-catalog-20260906'
OUT.mkdir(parents=True, exist_ok=True)
classification = json.loads((SOURCE / 'classification.json').read_text(encoding='utf-8-sig'))
VERSION = classification['version']
reference = {x['iataCode']: x for x in json.loads(gzip.decompress((DATA / 'airports-20260714.json.gz').read_bytes()))}
def persian(s):
    return s if s and re.search('[\u0621-\u063a\u0641-\u064a\u067e\u0686\u0698\u06a9\u06af\u06cc]', s) else None

cities, airports, memberships, audit = {}, {}, [], []
raw_counts = []
for mode in ('dom', 'int'):
    source = json.loads((SOURCE / f'airports-{mode}.json').read_text(encoding='utf-8-sig'))['cities']
    raw_counts.append((mode, len(source), sum(len(c['airports']) for c in source)))
    assert len({c['iataCode'] for c in source}) == len(source)
    seen = set()
    for c in source:
        city_code = c['iataCode']
        cities[city_code] = dict(city_code=city_code, city_name_fa=c['cityFaName'], city_name_en=c['cityName'],
            country_code=c['countryCode'], country_name_fa=c['countryFaName'], country_name_en=c['countryName'])
        retained = 0
        for a in c['airports']:
            code = a['iataCode']
            assert a['code'] == code and re.fullmatch('[A-Z]{3}', code)
            assert code not in seen, (mode, code)
            seen.add(code)
            if code in classification['excluded']:
                audit.append(f'Excluded {mode}/{city_code}/{code}: {classification["excluded"][code]}')
                continue
            retained += 1
            old = reference.get(code, {})
            row = dict(cities[city_code], iata_code=code, airport_name_fa=persian(a['faName']), airport_name_en=a['name'],
                fallback_fa=persian(old.get('airportNameFa')), icao_code=old.get('icaoCode'),
                latitude=old.get('latitude'), longitude=old.get('longitude'))
            airports[code] = row
            memberships.append(dict(city_code=city_code, airport_code=code, is_domestic=mode == 'dom',
                city_rank=c['rank'], airport_rank=a['rank']))
            for new_key, old_key in [('city_code','cityCode'),('country_code','countryCode'),('airport_name_en','airportNameEn')]:
                if old and old.get(old_key) != row[new_key]:
                    audit.append(f'JSON precedence {mode}/{code}: {new_key}: {old.get(old_key)!r} -> {row[new_key]!r}')
        assert retained, city_code

payload = json.dumps(dict(cities=list(cities.values()), airports=list(airports.values()), memberships=memberships), ensure_ascii=False)
assert '$catalog$' not in payload
sql = r'''-- Generated by tools/generate-flight-search-catalog.py. Do not edit generated SQL.
-- Schema migration must run first. This same transaction is used by the application Seeder.
BEGIN;
SELECT pg_advisory_xact_lock(620260906);
CREATE OR REPLACE FUNCTION pg_temp.flight_normalize(value text) RETURNS text
LANGUAGE sql IMMUTABLE AS $normalize$
 SELECT trim(regexp_replace(normalize(translate(regexp_replace(normalize(lower(value), NFD),
 '[̀-ًͯ-ٰٟ]', '', 'g'), 'يىك‌‍', 'ییک  '), NFC), '\s+', ' ', 'g'));
$normalize$;
DO $import$
DECLARE
 payload jsonb := $catalog$__PAYLOAD__$catalog$::jsonb;
 changed integer;
 added integer;
BEGIN
 IF EXISTS (SELECT 1 FROM flights.catalog_imports WHERE version = '__VERSION__') THEN
   RAISE NOTICE 'Catalogue __VERSION__ already applied';
   RETURN;
 END IF;
 CREATE TEMP TABLE stage_cities ON COMMIT DROP AS SELECT * FROM jsonb_to_recordset(payload->'cities') AS x(
  city_code varchar(3), city_name_fa text, city_name_en text, country_code varchar(2), country_name_fa text, country_name_en text);
 CREATE TEMP TABLE stage_airports ON COMMIT DROP AS SELECT * FROM jsonb_to_recordset(payload->'airports') AS x(
  iata_code varchar(3), city_code varchar(3), city_name_fa text, city_name_en text, country_code varchar(2),
  country_name_fa text, country_name_en text, airport_name_fa text, airport_name_en text, fallback_fa text,
  icao_code varchar(4), latitude numeric, longitude numeric);
 CREATE TEMP TABLE stage_memberships ON COMMIT DROP AS SELECT * FROM jsonb_to_recordset(payload->'memberships') AS x(
  city_code varchar(3), airport_code varchar(3), is_domestic boolean, city_rank integer, airport_rank integer);

 IF EXISTS (SELECT iata_code FROM stage_airports GROUP BY iata_code HAVING count(*) > 1)
 OR EXISTS (SELECT city_code FROM stage_cities GROUP BY city_code HAVING count(*) > 1)
 OR EXISTS (SELECT is_domestic, airport_code FROM stage_memberships GROUP BY is_domestic, airport_code HAVING count(*) > 1)
 OR EXISTS (SELECT 1 FROM stage_memberships m LEFT JOIN stage_cities c USING(city_code)
    LEFT JOIN stage_airports a ON a.iata_code=m.airport_code WHERE c.city_code IS NULL OR a.iata_code IS NULL)
 OR EXISTS (SELECT 1 FROM stage_cities c WHERE NOT EXISTS (SELECT 1 FROM stage_memberships m WHERE m.city_code=c.city_code))
 OR EXISTS (SELECT 1 FROM stage_airports WHERE iata_code !~ '^[A-Z]{3}$' OR country_code !~ '^[A-Z]{2}$'
    OR coalesce(airport_name_en,'')='' OR length(airport_name_en)>300 OR length(airport_name_fa)>300
    OR coalesce(city_name_fa,'')='' OR coalesce(city_name_en,'')='' OR length(city_name_fa)>200 OR length(city_name_en)>200
    OR coalesce(country_name_fa,'')='' OR coalesce(country_name_en,'')='' OR length(country_name_fa)>200 OR length(country_name_en)>200)
 THEN RAISE EXCEPTION 'Invalid flight catalogue staging data'; END IF;

 SELECT count(*) INTO changed FROM stage_airports s JOIN flights.airports a USING(iata_code);
 SELECT count(*) INTO added FROM stage_airports s WHERE NOT EXISTS (SELECT 1 FROM flights.airports a WHERE a.iata_code=s.iata_code);
 -- Preserve the first before-image; NULL means the airport did not exist.
 INSERT INTO flights.catalog_backups(version, table_name, row_key, row_data)
 SELECT '__VERSION__','airports',s.iata_code, CASE WHEN a.iata_code IS NULL THEN NULL ELSE to_jsonb(a) END
 FROM stage_airports s LEFT JOIN flights.airports a USING(iata_code);
 INSERT INTO flights.catalog_backups(version, table_name, row_key, row_data)
 SELECT '__VERSION__','search_cities',city_code,to_jsonb(c) FROM flights.search_cities c;
 INSERT INTO flights.catalog_backups(version, table_name, row_key, row_data)
 SELECT '__VERSION__','search_memberships',is_domestic::text||':'||city_code||':'||airport_code,to_jsonb(m)
 FROM flights.search_memberships m;

 INSERT INTO flights.airports(iata_code,icao_code,city_code,airport_name_fa,airport_name_en,city_name_fa,city_name_en,
  country_code,country_name_fa,country_name_en,latitude,longitude,is_popular,is_active,source_version,
  translation_source,search_text,imported_at_utc)
 SELECT s.iata_code,coalesce(a.icao_code,s.icao_code),s.city_code,
  coalesce(s.airport_name_fa, CASE WHEN a.airport_name_fa ~ '[ء-غف-يپچژکگی]' THEN a.airport_name_fa END,s.fallback_fa,s.airport_name_en),
  s.airport_name_en,s.city_name_fa,s.city_name_en,s.country_code,s.country_name_fa,s.country_name_en,
  coalesce(a.latitude,s.latitude),coalesce(a.longitude,s.longitude),true,true,'__VERSION__',
  CASE WHEN s.airport_name_fa IS NOT NULL THEN 'supplied-json' WHEN a.airport_name_fa ~ '[ء-غف-يپچژکگی]'
       THEN a.translation_source WHEN s.fallback_fa IS NOT NULL THEN 'reference-fallback' ELSE 'english-fallback' END,
  '',CURRENT_TIMESTAMP
 FROM stage_airports s LEFT JOIN flights.airports a USING(iata_code)
 ON CONFLICT(iata_code) DO UPDATE SET city_code=excluded.city_code,airport_name_fa=excluded.airport_name_fa,
  airport_name_en=excluded.airport_name_en,city_name_fa=excluded.city_name_fa,city_name_en=excluded.city_name_en,
  country_code=excluded.country_code,country_name_fa=excluded.country_name_fa,country_name_en=excluded.country_name_en,
  is_popular=excluded.is_popular,is_active=true,source_version=excluded.source_version,
  translation_source=excluded.translation_source,imported_at_utc=excluded.imported_at_utc;

 UPDATE flights.airports a SET search_text=pg_temp.flight_normalize(concat_ws(' ',a.iata_code,a.icao_code,
  a.city_code,a.airport_name_fa,a.airport_name_en,a.city_name_fa,a.city_name_en,a.country_name_fa,a.country_name_en))
 WHERE a.iata_code IN (SELECT iata_code FROM stage_airports);
 -- Rebuild only selectable membership; historical airports remain untouched outside this import.
 DELETE FROM flights.search_memberships;
 DELETE FROM flights.search_cities;
 INSERT INTO flights.search_cities SELECT * FROM stage_cities;
 INSERT INTO flights.search_memberships(city_code,airport_code,is_domestic,city_rank,airport_rank)
 SELECT city_code,airport_code,is_domestic,city_rank,airport_rank FROM stage_memberships;
 INSERT INTO flights.catalog_imports(version,applied_at_utc,report)
 VALUES('__VERSION__',CURRENT_TIMESTAMP,jsonb_build_object('rawDomesticCities',40,'rawDomesticEntries',40,
  'rawInternationalCities',40,'rawInternationalEntries',99,'airportsInserted',added,'airportsUpdated',changed,
  'cities',(SELECT count(*) FROM stage_cities),'memberships',(SELECT count(*) FROM stage_memberships)));
 RAISE NOTICE 'Flight catalogue applied: % added, % updated',added,changed;
END;
$import$;
COMMIT;
'''.replace('__PAYLOAD__',payload).replace('__VERSION__',VERSION)
(OUT/'02-data.sql').write_text(sql,encoding='utf-8')
report = ['# Flight search catalogue source audit', '', f'Version: {VERSION}', '',
    'JSON identity fields take precedence by explicit product decision. Source differences below are not silently corrected.', '',
    f'Raw counts: {raw_counts}',f'Unique retained airports: {len(airports)}; cities: {len(cities)}; memberships: {len(memberships)}.',
    f'International retained memberships: {sum(not m["is_domestic"] for m in memberships)}.', '', '## Source SHA-256', '']
for p in sorted(SOURCE.glob('*.json')):
    report.append(f'- {p.name}: `{hashlib.sha256(p.read_bytes()).hexdigest()}`')
report += ['', '## Classification and reference differences', ''] + ['- '+line for line in audit]
(OUT/'source-audit.md').write_text('\n'.join(report)+'\n',encoding='utf-8')
print(f'Generated catalogue: {len(cities)} cities, {len(airports)} airports, {len(memberships)} memberships')
