// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Refahi.Modules.Store.Infrastructure.Persistence.Context;

#nullable disable

namespace Refahi.Modules.Store.Infrastructure.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20260815184411_Store_AddVoucherSources")]
    partial class Store_AddVoucherSources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("store")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Aggregates.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ModuleId")
                        .IsUnique();

                    b.ToTable("carts", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Aggregates.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset?>("EndDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FinalPriceMinor")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("OriginalPriceMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("ProductId", "SupplierId");

                    b.HasIndex("ProductSessionId", "ProductId");

                    b.HasIndex("ProductVariantId", "ProductId");

                    b.HasIndex("ShopId", "SupplierId");

                    b.HasIndex("ProductId", "ShopId", "ProductVariantId", "ProductSessionId")
                        .IsUnique()
                        .HasDatabaseName("UX_offers_open_coordinate")
                        .HasFilter("\"IsDeleted\" = false AND \"EndDateUtc\" IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ProductId", "ShopId", "ProductVariantId", "ProductSessionId"), false);

                    b.HasIndex("ProductId", "ShopId", "IsActive", "IsDeleted", "StartDateUtc", "EndDateUtc");

                    b.ToTable("offers", "store", t =>
                        {
                            t.HasCheckConstraint("CK_offers_discount", "\"DiscountPercent\" >= 0 AND \"DiscountPercent\" <= 100");

                            t.HasCheckConstraint("CK_offers_original_price", "\"OriginalPriceMinor\" > 0");

                            t.HasCheckConstraint("CK_offers_window", "\"EndDateUtc\" IS NULL OR \"StartDateUtc\" < \"EndDateUtc\"");
                        });
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Aggregates.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<short>("FulfillmentMethod")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<short>("ProductType")
                        .HasColumnType("smallint");

                    b.Property<short>("SalesModel")
                        .HasColumnType("smallint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("StockCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("VoucherSourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("VoucherSourceId")
                        .HasFilter("\"VoucherSourceId\" IS NOT NULL");

                    b.HasIndex("SupplierId", "CategoryId");

                    b.ToTable("products", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Aggregates.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveredOrdersCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ManagerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("integer");

                    b.Property<string>("RepresentativeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RepresentativePhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<short>("ShopType")
                        .HasColumnType("smallint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("shops", "store", t =>
                        {
                            t.HasCheckConstraint("CK_shops_shop_type", "\"ShopType\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Aggregates.StoreOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<short>("DeliveryTimeSlot")
                        .HasColumnType("smallint");

                    b.Property<long>("DiscountAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("FinalAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InitiatorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<long>("OriginalAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("OtpDispatchStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("OtpExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtpReferenceCode")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("OtpVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PayableUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<short>("SalesChannel")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ShippingAddressId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("\"OrderId\" IS NOT NULL");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("SalesChannel", "ShopId", "CreatedAt");

                    b.ToTable("store_orders", "store", t =>
                        {
                            t.HasCheckConstraint("CK_store_orders_amounts", "\"OriginalAmountMinor\" >= \"FinalAmountMinor\" AND \"FinalAmountMinor\" > 0");
                        });
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Aggregates.VoucherSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultValidityDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<short>("RedemptionMode")
                        .HasColumnType("smallint");

                    b.Property<short>("SourceType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId", "IsActive");

                    b.HasIndex("SupplierId", "Title")
                        .IsUnique();

                    b.ToTable("voucher_sources", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("BannerType")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModuleId")
                        .HasFilter("\"ModuleId\" IS NOT NULL");

                    b.HasIndex("ShopId")
                        .HasFilter("\"ShopId\" IS NOT NULL");

                    b.ToTable("banners", "store", t =>
                        {
                            t.HasCheckConstraint("CK_banners_owner_xor", "(\"ModuleId\" IS NULL) <> (\"ShopId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<long>("OriginalUnitPriceMinor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<long>("UnitPriceMinor")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("UsageDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OfferId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopId");

                    b.ToTable("cart_items", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.DailyDeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ModuleId")
                        .HasFilter("\"ModuleId\" IS NOT NULL");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopId")
                        .HasFilter("\"ShopId\" IS NOT NULL");

                    b.ToTable("daily_deals", "store", t =>
                        {
                            t.HasCheckConstraint("CK_daily_deals_owner_xor", "(\"ModuleId\" IS NULL) <> (\"ShopId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_images", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.ProductSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SoldCount")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId", "Date");

                    b.ToTable("product_sessions", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.ProductSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_specifications", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<short>("CapacityType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StockCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("VoucherSourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("VoucherSourceId")
                        .HasFilter("\"VoucherSourceId\" IS NOT NULL");

                    b.HasIndex("ProductId", "CapacityType");

                    b.HasIndex("ProductId", "FromDate", "ToDate");

                    b.ToTable("product_variants", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.ProductVariantCombination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariantAttributeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariantAttributeValueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("VariantAttributeValueId");

                    b.ToTable("product_variant_combinations", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId", "UserId")
                        .IsUnique();

                    b.ToTable("reviews", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.StoreModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("modules", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.StoreOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgreementCategoryTermId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<long>("CommissionAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<long?>("DeclaredGrossAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<short>("DeliveryMethod")
                        .HasColumnType("smallint");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<long>("FinalUnitPriceMinor")
                        .HasColumnType("bigint");

                    b.Property<short>("FulfillmentMethod")
                        .HasColumnType("smallint");

                    b.Property<long>("GrossAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<long>("OriginalUnitPriceMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<short>("ProductType")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<short>("SalesChannel")
                        .HasColumnType("smallint");

                    b.Property<short>("SalesModel")
                        .HasColumnType("smallint");

                    b.Property<string>("SessionTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceCartItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoreOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<long>("UnitPriceMinor")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("UsageDate")
                        .HasColumnType("date");

                    b.Property<string>("VariantTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("VoucherDefaultValidityDays")
                        .HasColumnType("integer");

                    b.Property<short?>("VoucherRedemptionMode")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("VoucherSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("VoucherSourceTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<short?>("VoucherSourceType")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("OfferId")
                        .HasFilter("\"OfferId\" IS NOT NULL");

                    b.HasIndex("StoreOrderId");

                    b.HasIndex("VoucherSourceId")
                        .HasFilter("\"VoucherSourceId\" IS NOT NULL");

                    b.ToTable("store_order_items", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VariantAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("variant_attributes", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VariantAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("VariantAttributeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VariantAttributeId");

                    b.ToTable("variant_attribute_values", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeCiphertext")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("RedeemedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RedeemedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RedeemedShopId")
                        .HasColumnType("uuid");

                    b.Property<string>("RedeemedShopName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<short>("RedemptionMode")
                        .HasColumnType("smallint");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<short>("SourceType")
                        .HasColumnType("smallint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("StoreOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoreOrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("VoucherSourceCodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VoucherSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("VoucherSourceTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("VoucherSourceCodeId")
                        .IsUnique()
                        .HasFilter("\"VoucherSourceCodeId\" IS NOT NULL");

                    b.HasIndex("VoucherSourceId");

                    b.HasIndex("StoreOrderId", "Status");

                    b.HasIndex("StoreOrderItemId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("SupplierId", "CodeHash")
                        .IsUnique();

                    b.HasIndex("UserId", "IssuedAtUtc");

                    b.ToTable("vouchers", "store", t =>
                        {
                            t.HasCheckConstraint("CK_vouchers_sequence", "\"SequenceNumber\" > 0");
                        });
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherCodeAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReservedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("StoreOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoreOrderItemId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("VoucherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoucherSourceCodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoreOrderId");

                    b.HasIndex("VoucherId")
                        .IsUnique()
                        .HasFilter("\"VoucherId\" IS NOT NULL");

                    b.HasIndex("VoucherSourceCodeId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (1, 2)");

                    b.HasIndex("Status", "ReservedUntilUtc");

                    b.HasIndex("StoreOrderItemId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("voucher_code_allocations", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherCodeImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("integer");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("VoucherSourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoucherSourceId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("voucher_code_import_batches", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.HasIndex("VoucherId", "Channel")
                        .IsUnique();

                    b.ToTable("voucher_deliveries", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("RedeemedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VendorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoucherId");

                    b.HasIndex("VendorUserId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("SupplierId", "ShopId", "RedeemedAtUtc");

                    b.ToTable("voucher_redemptions", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherRefundOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("StoreOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("VoucherSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("StoreOrderId")
                        .IsUnique();

                    b.ToTable("voucher_refund_overrides", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherRefundOverrideAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PaymentAction")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("VoucherRefundOverrideId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoucherRefundOverrideId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("voucher_refund_override_attempts", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherSourceCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeCiphertext")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("VoucherSourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId", "CodeHash")
                        .IsUnique();

                    b.HasIndex("VoucherSourceId", "Status", "ExpiresAtUtc", "RegisteredAtUtc");

                    b.ToTable("voucher_source_codes", "store");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Aggregates.Offer", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId", "SupplierId")
                        .HasPrincipalKey("Id", "SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Refahi.Modules.Store.Domain.Entities.ProductSession", null)
                        .WithMany()
                        .HasForeignKey("ProductSessionId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Refahi.Modules.Store.Domain.Entities.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId", "SupplierId")
                        .HasPrincipalKey("Id", "SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Aggregates.Product", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.VoucherSource", null)
                        .WithMany()
                        .HasForeignKey("VoucherSourceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.Banner", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Entities.StoreModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.DailyDeal", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Entities.StoreModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.ProductSession", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.Product", null)
                        .WithMany("Sessions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.ProductSpecification", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.Product", null)
                        .WithMany("Specifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.VoucherSource", null)
                        .WithMany()
                        .HasForeignKey("VoucherSourceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.ProductVariantCombination", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Entities.ProductVariant", null)
                        .WithMany("Combinations")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.StoreOrderItem", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.StoreOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("StoreOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VariantAttribute", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.Product", null)
                        .WithMany("VariantAttributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VariantAttributeValue", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Entities.VariantAttribute", null)
                        .WithMany("Values")
                        .HasForeignKey("VariantAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.Voucher", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.StoreOrder", null)
                        .WithMany()
                        .HasForeignKey("StoreOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Refahi.Modules.Store.Domain.Entities.StoreOrderItem", null)
                        .WithMany()
                        .HasForeignKey("StoreOrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Refahi.Modules.Store.Domain.Entities.VoucherSourceCode", null)
                        .WithMany()
                        .HasForeignKey("VoucherSourceCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.VoucherSource", null)
                        .WithMany()
                        .HasForeignKey("VoucherSourceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherCodeAllocation", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.StoreOrder", null)
                        .WithMany()
                        .HasForeignKey("StoreOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Refahi.Modules.Store.Domain.Entities.StoreOrderItem", null)
                        .WithMany()
                        .HasForeignKey("StoreOrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Refahi.Modules.Store.Domain.Entities.Voucher", null)
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Refahi.Modules.Store.Domain.Entities.VoucherSourceCode", null)
                        .WithMany()
                        .HasForeignKey("VoucherSourceCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherCodeImportBatch", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.VoucherSource", null)
                        .WithMany()
                        .HasForeignKey("VoucherSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherDelivery", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Entities.Voucher", null)
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherRedemption", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Entities.Voucher", null)
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherRefundOverride", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.StoreOrder", null)
                        .WithMany()
                        .HasForeignKey("StoreOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherRefundOverrideAttempt", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Entities.VoucherRefundOverride", null)
                        .WithMany()
                        .HasForeignKey("VoucherRefundOverrideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VoucherSourceCode", b =>
                {
                    b.HasOne("Refahi.Modules.Store.Domain.Aggregates.VoucherSource", null)
                        .WithMany()
                        .HasForeignKey("VoucherSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Aggregates.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Aggregates.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Sessions");

                    b.Navigation("Specifications");

                    b.Navigation("VariantAttributes");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Aggregates.StoreOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.ProductVariant", b =>
                {
                    b.Navigation("Combinations");
                });

            modelBuilder.Entity("Refahi.Modules.Store.Domain.Entities.VariantAttribute", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
